# Generated by Django 5.1 on 2024-10-03 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCategory',
            new_name='PostCommunity',
        ),
        migrations.RenameField(
            model_name='postcommunity',
            old_name='category_name',
            new_name='community_name',
        ),
        migrations.AlterModelTable(
            name='postcommunity',
            table='forum_postcommunity',
        ),
    ]
