# Generated by Django 5.1 on 2024-10-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_postcategory_postcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='community',
        ),
    ]
