# Generated by Django 5.1 on 2024-10-12 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_remove_pollchoice_votes_pollvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='poll_title',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='time_created',
        ),
        migrations.AddField(
            model_name='poll',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='forum.post'),
        ),
    ]
