# Generated by Django 5.1 on 2024-10-29 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_poll_poll_title_remove_poll_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='forum.poll'),
        ),
        migrations.AlterField(
            model_name='pollvote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='forum.pollchoice'),
        ),
    ]
