# Generated by Django 5.1.2 on 2024-11-16 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('other', 'Other')], default='Inappropriate Content', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('user', 'post')},
        ),
    ]
