# Generated by Django 5.1.2 on 2024-11-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0018_report_comment_alter_report_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlikes',
            name='is_liked',
            field=models.BooleanField(default=True),
        ),
    ]
