# Generated by Django 5.1.2 on 2024-12-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_postlikes_is_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommunity',
            name='community_sidebar_logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
