# Generated by Django 5.1.2 on 2024-12-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_postcommunity_community_sidebar_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommunity',
            name='community_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='postcommunity',
            name='community_post_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
