# Generated by Django 5.1.2 on 2024-12-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_postcommunity_community_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommunity',
            name='community_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
