# Generated by Django 5.1.4 on 2025-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0023_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment_body',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='postcommentreply',
            name='reply_body',
            field=models.CharField(max_length=500),
        ),
    ]
