# Generated by Django 5.1 on 2024-08-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_email_verified_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
    ]
