# Generated by Django 5.1 on 2024-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
